replicaCount: 1

image:
  repository: ghcr.io/matheus06/product-service
  tag: "dev-678aaf5"

service:
  type: ClusterIP

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: product.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Development"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel-collector:4317"
  - name: SEED_DATA
    value: "true"
  - name: MONGODB_CONNECTION_STRING
    value: "mongodb://root:local-dev-password@mongodb-ubuntu:27017/microservices?authSource=admin"

vault:
  enabled: true
  address: "http://vault-ubuntu:8200"
  role: "product-service"
  secretPath: "database/creds/microservices-role"
  mongodbHost: "mongodb-ubuntu"
  mongodbPort: "27017"
  mongodbDatabase: "microservices"

metrics:
  enabled: false
