replicaCount: 1

image:
  repository: ghcr.io/matheus06/product-service
  tag: "dev-678aaf5"

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Development"
  - name: SEED_DATA
    value: "true"

vault:
  enabled: true
  address: "http://vault:8200"
  role: "product-service"
  secretPath: "database/creds/microservices-role"
  mongodbHost: "mongodb"
  mongodbPort: "27017"
  mongodbDatabase: "microservices"
