replicaCount: 1

image:
  repository: ghcr.io/matheus06/order-service
  tag: "dev-6daf429"

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Development"
  - name: ProductServiceUrl
    value: "http://product-service:80"
  - name: SEED_DATA
    value: "true"

vault:
  enabled: true
  address: "http://vault:8200"
  role: "order-service"
  secretPath: "database/creds/microservices-role"
  mongodbHost: "mongodb"
  mongodbPort: "27017"
  mongodbDatabase: "microservices"
