replicaCount: 3

image:
  repository: ghcr.io/matheus06/order-service
  tag: "v1.0.1"

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Production"
  - name: ProductServiceUrl
    value: "http://product-service:80"
  - name: SEED_DATA
    value: "true"

vault:
  enabled: true
  address: "http://vault:8200"
  role: "order-service"
  secretPath: "database/creds/microservices-role"
  mongodbHost: "mongodb"
  mongodbPort: "27017"
  mongodbDatabase: "microservices"
